apiVersion: v1
kind: Secret
metadata:
  name: kino-secret
  namespace: kino-kiii
type: Opaque
data:
  TMDB_API_KEY: eW91cl90bWRiX2FwaV9rZXk=
  SPRING_DATASOURCE_USERNAME: a2lub191c2Vy
  SPRING_DATASOURCE_PASSWORD: a2lub19wYXNzd29yZA==
