spring.application.name=Kino

tmdb.base-url=https://api.themoviedb.org/3
tmdb.api-key=${TMDB_API_KEY}
tmdb.language=en-US
tmdb.include-adult=false
tmdb.image-base-url=https://image.tmdb.org/t/p/w500

spring.config.import=optional:file:.env[.properties]
management.endpoints.web.exposure.include=mappings

kino.cors.allowed-origins=http://localhost:4200,https://kino-git-master-riste-gjorgjievs-projects-5ec22153.vercel.app,https://*.vercel.app

logging.level.mk.ukim.finki.wp.kino.config.LoggingFilter=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %logger{36} : %m%n