spring.application.name=Kino
tmdb.base-url=https://api.themoviedb.org/3
tmdb.api-key=test-api-key
tmdb.language=en-US
tmdb.include-adult=false
tmdb.image-base-url=https://image.tmdb.org/t/p/w500

kino.cors.allowed-origins=http://localhost:4200

