spring.application.name=Kino

tmdb.base-url=https://api.themoviedb.org/3
tmdb.api-key=${TMDB_API_KEY}
tmdb.language=en-US
tmdb.include-adult=false
tmdb.image-base-url=https://image.tmdb.org/t/p/w500

spring.config.import=optional:file:.env[.properties]
management.endpoints.web.exposure.include=mappings